// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcmhsneyivchstmkbbla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbWhzbmV5aXZjaHN0bWtiYmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzY4MDgsImV4cCI6MjA2Njg1MjgwOH0.qw39j9ZaTHxq8UqCMBwYM-noW5by6ybbvvlBwmmC9MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});